development:
  adapter: mysql
  database: police_dev
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: police_test
  username: root
  password: 

production:
  adapter: mysql
  database: police_live
  username: root
  password: QvbzMWN2.wsg
  host: localhost